language: node_js

env:
  - LINUX_CXX=g++-4.8

node_js:
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
  - "11"

before_script:
  - npm install

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

branches:
  only:
    - master

cache:
  directories:
    - ~/.npm

install: true

script: npm test
